# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


deploy:
  # working_directory: ~/synth
  # docker:
  #   - image: circleci/node:9-browsers
  steps:
    # Log the current branch
    - run: echo ${CIRCLE_BRANCH}
    - run:
        name: Update Code in Droplet
        # note: DROPLET_USER / DROPLET_IP vars are added in the CircleCI dashboard
        command: rsync -e "ssh -o StrictHostKeyChecking=no" -r *.js ${DROPLET_USER}@${DROPLET_IP}:${DROPLET_PATH}
    - run: pm2 restart ascii

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - deploy:
          # requires:
          #   - build
