# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/
    environment:
      BUILD_DIR: ~/
    steps:
      - run: apk update && apk add git
      - checkout
      # - run: git submodule sync && git submodule update --init
      # - run: curl -L https://github.com/bep/s3deploy/releases/download/v2.0.1/s3deploy_2.0.1_Linux-64bit.tar.gz | tar xvz
      # - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - add_ssh_keys:
          fingerprints:
            - "03:01:31:a6:2c:01:00:92:31:b4:9c:d9:c4:03:4e:04"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -azP --exclude 'ASS/' --exclude '.*' $BUILD_DIR root@68.183.119.128:/var/www/maladjusted
            else
              echo "Not master branch, dry run only"
            fi
